elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  volumes:
    - ./esdata:/usr/share/elasticsearch/data:Z

logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d:ro,Z
  ports:
    - "5000:5000"
    - "42185:42185/udp"
    - "42185:42185/tcp"
  links:
    - elasticsearch

kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/:ro,Z
  links:
    - elasticsearch

nginx:
  image: nginx:latest
  volumes:
    - ./nginx/config:/etc/nginx/conf.d:ro,Z
    - ./nginx/htpasswd.users:/etc/nginx/htpasswd.users:ro,Z
  ports:
    - "5601:5601"
  links:
    - kibana
